language: generic
sudo: required
services:
  - docker

addons:
  apt:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    sources:
      - sourceline: "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        key_url: https://download.docker.com/linux/ubuntu/gpg

before_install:
  - docker-compose version


script:
  - curl localhost -s
