language: php

#services:
#  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  - DOCKER_COMPOSE_VERSION=1.24.0

before_install:
  - docker version
  - docker-compose version


script:
  - curl localhost -s
