language: php

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce
      - htop
env:
  - DOCKER_COMPOSE_VERSION=1.24.0

before_install:
  - sudo apt install mc -y
  - docker version
  - docker-compose version


script:
  - curl localhost -s
